apiVersion: v1
kind: ReplicationController
metadata:
    name: myrc
spec:
    replicas: 5 
    selector: 
        app:  web
    template:
        metadata:
              name: "myrc_pod"
              labels: 
                  app: web
        spec: 
                  containers:
                  - name:  "myrc-container"
                    image: "vimal13/apache-webserver-php"